// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghbapymbjqmnefoxvnoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoYmFweW1ianFtbmVmb3h2bm9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDkwNTUsImV4cCI6MjA2NTIyNTA1NX0.7R3IkBYYgkpg2hnWL8bS4RemGqNKad3G_MK-4ndEv5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);